BookWeb/Areas/Admin/Controllers/CompanyController.cs
using BookWeb.DataAccess.Repository.IRepository;
using BookWeb.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookWeb.Areas.Admin.Controllers
{
    public class CompanyController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public CompanyController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            List<Company> Companys = _unitOfWork.Company.GetAll().ToList();

            return View(Companys);
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            IEnumerable<SelectListItem> categoryList = _unitOfWork.Category.GetAll()
              .Select(u => new SelectListItem()
              {
                  Text = u.Name,
                  Value = u.Id.ToString(),
              });            

            if (!id.HasValue || id == 0)
            {
                // create
                return View(new Company());
            }

            // Update

            Company? Company = _unitOfWork.Company.Get(x => x.Id == id.Value);

            if (Company == null)
            {
                return BadRequest();
            }

            return View(Company);
        }   

        [HttpPost]
        public IActionResult Upsert(Company company)
        {
            if (!ModelState.IsValid) 
            {
                return View(new Company());
            }

            if (company == null)
            {
                return BadRequest();
            }

            // Create
            if (company.Id == 0)
            {                

                _unitOfWork.Company.Add(new Company());
                _unitOfWork.Save();

                TempData["success"] = "Company created successfully";
                
                return RedirectToAction("Index");
            }

        
            _unitOfWork.Company.Update(company);
            _unitOfWork.Save();

            TempData["success"] = "Company edited successfully";

            return RedirectToAction("Index");
        }
      
        #region API CALLS

        [HttpGet]
        public IActionResult GetAll(int id)
        {
            List<Company> Companys = _unitOfWork.Company.GetAll().ToList();

            return Json(new { data = Companys });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            if (!id.HasValue)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var CompanyToDeleted = _unitOfWork.Company.Get(u => u.Id == id.Value);

            if (CompanyToDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            _unitOfWork.Company.Remove(CompanyToDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Deleting successfully" });
        }

        #endregion
    }
}

BookWeb/Areas/Admin/Controllers/ProductController.cs
using BookWeb.DataAccess.Repository.IRepository;
using BookWeb.Models;
using BookWeb.Models.ViewModels;
using BookWeb.Utility.Helpers;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace BookWeb.Areas.Admin.Controllers
{
    public class ProductController : BaseController
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public ProductController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnvironment = webHostEnvironment;
        }

        public IActionResult Index()
        {
            List<Product> products = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();

            return View(products);
        }

        [HttpGet]
        public IActionResult Upsert(int? id)
        {
            IEnumerable<SelectListItem> categoryList = _unitOfWork.Category.GetAll()
              .Select(u => new SelectListItem()
              {
                  Text = u.Name,
                  Value = u.Id.ToString(),
              });            

            var productVm = new ProductVM()
            {
                Product = new(),
                CategoryList = categoryList
            };

            if (!id.HasValue || id == 0)
            {
                // create
                return View(productVm);
            }

            Product? product = _unitOfWork.Product.Get(x => x.Id == id.Value);

            if (product == null)
            {
                return BadRequest();
            }

            if (product.ImageUrl != null)
            {
                ViewBag.ProductUrl = FileHelper.NormalizeFilePathToWebRootPath(product.ImageUrl);
            }

            productVm.Product = product;

            return View(productVm);
        }   

        [HttpPost]
        public IActionResult Upsert(ProductVM productVm, IFormFile? file)
        {
            if (!ModelState.IsValid) 
            {
                productVm.CategoryList = _unitOfWork.Category.GetAll()
                    .Select(x => new SelectListItem()
                    {
                        Text= x.Name,
                        Value = x.Id.ToString(),
                    });               

                return View(productVm);
            }

            if (productVm == null)
            {
                return BadRequest();
            }

            if (file != null)
            {
                string fileName = Guid.NewGuid().ToString() + Path.GetExtension(file.FileName);
                string productPath = Path.Combine(_webHostEnvironment.WebRootPath, @"images\product");

                if (!string.IsNullOrEmpty(productVm.Product.ImageUrl))
                {
                    // delete the old image
                    var oldImagePath = Path.Combine(_webHostEnvironment.WebRootPath, productVm.Product.ImageUrl.TrimStart('\\'));

                    if (System.IO.File.Exists(oldImagePath))
                    {
                        System.IO.File.Delete(oldImagePath);
                    }

                }

                using (var fileStream = new FileStream(Path.Combine(productPath, fileName), FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }

                productVm.Product.ImageUrl = @"images\product\" + fileName;
            
            }

            // Create
            if (productVm.Product.Id == 0)
            {                

                _unitOfWork.Product.Add(productVm.Product);
                _unitOfWork.Save();

                TempData["success"] = "Product created successfully";
                
                return RedirectToAction("Index");
            }

            Product product = productVm.Product;

            _unitOfWork.Product.Update(product);
            _unitOfWork.Save();

            TempData["success"] = "Product edited successfully";

            return RedirectToAction("Index");
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll(int id)
        {
            List<Product> products = _unitOfWork.Product.GetAll(includeProperties: "Category").ToList();

            return Json(new { data = products });
        }

        [HttpDelete]
        public IActionResult Delete(int? id)
        {
            if (!id.HasValue)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var productToDeleted = _unitOfWork.Product.Get(u => u.Id == id.Value);

            if (productToDeleted == null)
            {
                return Json(new { success = false, message = "Error while deleting" });
            }

            var oldImagePath =
                Path.Combine(_webHostEnvironment.WebRootPath,
                             productToDeleted.ImageUrl!.TrimStart('\\'));

            if (System.IO.File.Exists(oldImagePath))
            {
                System.IO.File.Delete(oldImagePath);
            }

            _unitOfWork.Product.Remove(productToDeleted);
            _unitOfWork.Save();

            return Json(new { success = true, message = "Deleting successfully" });
        }

        #endregion
    }
}

BookWeb/Areas/Admin/Controllers/UserController.cs
using BookWeb.DataAccess.Data;
using BookWeb.DataAccess.Repository.IRepository;
using BookWeb.Models;
using BookWeb.Models.ViewModels;
using BookWeb.Utility;
using BookWeb.Utility.Helpers;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.ComponentModel.Design;
using System.Linq;

namespace BookWeb.Areas.Admin.Controllers
{
    public class UserController : BaseController
    {
        private readonly ApplicationDbContext _db;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IWebHostEnvironment _webHostEnvironment;
        private readonly List<IdentityRole> _roles;

        public UserController(ApplicationDbContext db, 
                              RoleManager<IdentityRole> roleManager, 
                              UserManager<ApplicationUser> userManager, 
                              IWebHostEnvironment webHostEnvironment)
        {
            _db = db;
            _roleManager = roleManager;
            _userManager = userManager;
            _webHostEnvironment = webHostEnvironment;
            _roles = _roleManager.Roles.ToList();
        }

        public IActionResult Index()
        {            
            return View();
        }

        [HttpGet]
        public IActionResult RoleManagement(string userId)
        {
            ApplicationUser? user = _db.Users.FirstOrDefault(u => u.Id == userId);

            if (user == null)       
            {
                return NotFound();
            }

            List<IdentityUserRole<string>> userRoles = _db.UserRoles.ToList();
            List<Company> companies = _db.Companies.ToList();

            IdentityUserRole<string> userRoleOfCurrentUser = userRoles.Where(r => r.UserId == user.Id).First();
            Company? companyOfCurrentUser = companies.FirstOrDefault(c => c.Id == user.CompanyId);

            user.Name = user.Name + $" ({_roles.First(r => r.Id == userRoleOfCurrentUser.RoleId).Name})";

            UserVM userVm = new()
            {
                ApplicationUser = user,
                RoleId = _roles.First(r => r.Id == userRoleOfCurrentUser.RoleId)!.Id,
                CompanyId = companyOfCurrentUser == null ? string.Empty : companyOfCurrentUser.Id.ToString(),
                Companies = companies,
                Roles = _roles
            };


            return View(userVm);
        }

        [HttpPost]
        public IActionResult RoleManagement(UserVM userVm)
        {
            if (userVm.RoleId == null)
            {
                return NotFound();
            }

            ApplicationUser? userFromDb = _userManager.FindByIdAsync(userVm.UserID).GetAwaiter().GetResult();

            if (userFromDb == null)
            {
                return NotFound();
            }

            UpdateRoleUser(userFromDb, userVm.RoleId).GetAwaiter().GetResult();

            UpsertCompanyUser(userVm.CompanyId, userFromDb);

            TempData["success"] = "Update Role Successfully!";

            return RedirectToAction(nameof(Index));
        }

        private async Task UpdateRoleUser(ApplicationUser userFromDb, string? newRoleId) 
        {            
            IdentityUserRole<string>? oldUserRoleFromDb = _db.UserRoles.Where(r => r.UserId == userFromDb.Id).FirstOrDefault();

            if (oldUserRoleFromDb != null &&
                newRoleId != null &&
                newRoleId != oldUserRoleFromDb.RoleId)
            {
                var oldRole = _roles.FirstOrDefault(r => r.Id == oldUserRoleFromDb.RoleId);
                var newRole = _roles.FirstOrDefault(r => r.Id == newRoleId);

                if (oldRole != null && newRole != null)
                {
                    await _userManager.RemoveFromRoleAsync(userFromDb, oldRole.Name!);
                    await _userManager.AddToRoleAsync(userFromDb, newRole.Name!);
                }
            }
        }

        private void UpsertCompanyUser(string? newCompanyId, ApplicationUser userFromDb)
        {            
            IdentityUserRole<string>? oldUserRoleFromDb = _db.UserRoles.Where(r => r.UserId == userFromDb.Id).FirstOrDefault();

            IdentityRole? roleCurrentUser = null;

            if (oldUserRoleFromDb != null)
            {
                roleCurrentUser = _roles.FirstOrDefault(r => r.Id == oldUserRoleFromDb.RoleId);
            }

            if (newCompanyId != null && roleCurrentUser != null && roleCurrentUser.Name == SD.Role_Company)
            {
                var companyIdInt = Int32.Parse(newCompanyId);

                if (userFromDb.CompanyId != null)
                {
                    // update
                    userFromDb.CompanyId = companyIdInt;
                    _db.Users.Update(userFromDb);
                }
                else
                {
                    // create
                    userFromDb.CompanyId = companyIdInt;
                }
                
            }
            else
            {
                userFromDb.CompanyId = null;
            }
            
            _db.SaveChanges();
        }

        #region API CALLS

        [HttpGet]
        public IActionResult GetAll()
        {            
            List<ApplicationUser> users = _db.ApplicationUsers.Include(u => u.Company).ToList();

            var userRoles = _db.UserRoles.ToList();
            var roles = _db.Roles.ToList();

            // Handling display the user has not belong to company 
            foreach (var user in users)
            {
                var roleId = userRoles.FirstOrDefault(u => u.UserId == user.Id).RoleId;
                var role = roles.FirstOrDefault(u => u.Id == roleId);

                user.Role = role.Name;

                if (user.Company == null)
                {
                    user.Company = new Company()
                    {
                        Name = ""
                    };
                }
            }

            return Json(new { data = users });
        }

        [HttpPost]
        public IActionResult LockUnlock([FromBody] string? id)
        {
            var objFromDb = _db.ApplicationUsers.FirstOrDefault(u => u.Id == id);

            if (objFromDb == null)
            {
                return Json(new { success = false, message = "Error while Locking/Unlocking"});
            }

            if (objFromDb.LockoutEnd != null && objFromDb.LockoutEnd > DateTime.Now)
            {
                // user is currently locked and we need to unlock them
                objFromDb.LockoutEnd = DateTime.Now;
            } else
            {
                objFromDb.LockoutEnd = DateTime.Now.AddDays(1_000);
            }

            _db.SaveChanges();

            return Json(new { success = true, message = "Operation successfully" });
        }

        #endregion
    }
}

BookWeb/ViewComponents/ShoppingCartViewComponent.cs
using BookWeb.DataAccess.Repository.IRepository;
using BookWeb.Utility;
using Microsoft.AspNetCore.Mvc;
using System.Security.Claims;

namespace BookWeb.ViewComponents
{
    public class ShoppingCartViewComponent : ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public ShoppingCartViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var claimsIdentity = (ClaimsIdentity) User.Identity;

            var userId = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);

            if (userId != null)
            {
                if (HttpContext.Session.GetInt32(SD.SessionCart) == null)
                {
                    HttpContext.Session.SetInt32(SD.SessionCart,
                        _unitOfWork.ShoppingCart.GetAll(u => u.ApplicationUserId == userId.Value).Count());
                }

                return View(HttpContext.Session.GetInt32(SD.SessionCart));
            }
            
            // logout, ...
            HttpContext.Session.Clear();
            return View(0);
        }
    }
}

BookWeb/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http

@inject IHttpContextAccessor IHttpContextAccessor

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BookWeb</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/BookWeb.styles.css" asp-append-version="true" />
    <!-- Toastr -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.css" integrity="sha512-3pIirOrwegjM6erE5gPSwkUzO+3cTjpnV9lexlNZqvupR64iZBnOOTiiLPb9M36zpMScbmUNIcHUqKD47M719g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    
    <link rel="stylesheet" href="//cdn.datatables.net/1.13.4/css/jquery.dataTables.min.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">BookWeb</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav me-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        
                        <li class="nav-item">
                            <a class="nav-link" asp-area="Admin" asp-controller="Order" asp-action="Index">Manage Order</a>
                        </li>
                            
                        @if (User.IsInRole(SD.Role_Admin))
                        {  
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <ul class="dropdown-menu">
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Company" asp-action="Index">Company</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    </li>

                                    <li><hr class="dropdown-divider" /></li>

                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Identity" asp-page="/Account/Register">Create User</a>
                                    </li>
                                    <li class="nav-item">
                                        <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">Manage User</a>
                                    </li>
                                </ul>
                            </li>
                        }

                        <li class="nav-item">
                            <a class="nav-link" asp-area="Customer" asp-controller="Cart" asp-action="Index">
                                @await Component.InvokeAsync("ShoppingCart")
                            </a>
                        </li>

                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_Notification" />
            @RenderBody()
        </main>
    </div>


    <footer class="border-top footer bg-primary text-muted">
        <div class="container">
            &copy; 2023 - BookWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
 
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="//cdn.datatables.net/1.13.4/js/jquery.dataTables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>    
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

BookWeb/Views/Shared/_Notification.cshtml
@if (TempData["success"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script type="text/javascript">
        toastr.success('@TempData["success"]');
    </script>
}

@if (TempData["error"] != null)
{
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js" integrity="sha512-VEd+nq25CkR676O+pLBnDW09R7VQX9Mdiij052gVCp5yVH3jGtH70Ho/UUv4mJDsEdTvqRCFZg0NKGiojGnUCw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    
    <script type="text/javascript">
        toastr.error('@TempData["error"]');
    </script>
}